version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: roster-app
    container_name: roster-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:FrDCh6h/B0fInE3GYpvUYlRZjNFAPPIiwD/xB/N4V54=
